
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1E8BA3D46D4C83A4B4488A567A801F65'
    
_lr_action_items = {'AND':([9,20,],[14,24,]),'THEN':([26,],[30,]),'WHAT':([0,],[1,]),'COMPOBJ':([11,21,28,29,],[17,25,31,32,]),'IS':([0,1,9,16,33,],[2,7,15,22,34,]),'OBJECT':([7,13,15,22,23,34,],[12,18,20,26,27,35,]),'ARE':([19,],[23,]),'IF':([0,],[6,]),'NOT':([7,15,23,24,],[11,21,28,29,]),'THE':([0,2,6,],[5,8,10,]),'$end':([3,4,12,17,18,20,25,27,31,32,35,],[-1,0,-9,-10,-8,-2,-3,-4,-5,-6,-7,]),'SUBJECT':([5,8,10,14,30,],[9,13,16,19,33,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inquiry':([0,],[3,]),'statement':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> inquiry','statement',1,'p_statement','Parser.py',21),
  ('statement -> THE SUBJECT IS OBJECT','statement',4,'p_statement_1','Parser.py',28),
  ('statement -> THE SUBJECT IS NOT COMPOBJ','statement',5,'p_statement_2','Parser.py',39),
  ('statement -> THE SUBJECT AND SUBJECT ARE OBJECT','statement',6,'p_statement_3','Parser.py',50),
  ('statement -> THE SUBJECT AND SUBJECT ARE NOT COMPOBJ','statement',7,'p_statement_4','Parser.py',68),
  ('statement -> THE SUBJECT IS OBJECT AND NOT COMPOBJ','statement',7,'p_statement_5','Parser.py',86),
  ('statement -> IF THE SUBJECT IS OBJECT THEN SUBJECT IS OBJECT','statement',9,'p_hypothesis_6','Parser.py',98),
  ('inquiry -> IS THE SUBJECT OBJECT','inquiry',4,'p_element_inquiry','Parser.py',112),
  ('inquiry -> WHAT IS OBJECT','inquiry',3,'p_element_inquiry2','Parser.py',123),
  ('inquiry -> WHAT IS NOT COMPOBJ','inquiry',4,'p_element_inquiry3','Parser.py',133),
]
